spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/DrawingAppDB
    username: postgres
    password: azor123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mail.ru
    port: 465
    username: "drawing-battle@mail.ru"
    password: "NBXxxggPRMKgrvNExKhA"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: health
gameConstants:
  group:
    createPrice: 5000
    maxMemberCount: 30
  energy:
    valueMax: 15
    recoveryTime: 10
jwt:
  secret: "62A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
  expiration: 360000000000
server:
  port: 8080